# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: position-tracker
# spec:
#   selector:
#     matchLabels:
#       app: position-tracker
#   replicas: 1
#   template: # template for the pods
#     metadata:
#       labels:
#         app: position-tracker
#     spec:
#       containers:
#       - name: position-tracker
#         image: richardchesterwood/k8s-fleetman-position-tracker:release3
#         env:
#         - name: SPRING_PROFILES_ACTIVE
#           value: production-microservice


#---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: api-gateway
# spec:
#   selector:
#     matchLabels:
#       app: api-gateway
#   replicas: 1
#   template: # template for the pods
#     metadata:
#       labels:
#         app: api-gateway
#     spec:
#       containers:
#       - name: api-gateway
#         image: richardchesterwood/k8s-fleetman-api-gateway:release2
#         env:
#         - name: SPRING_PROFILES_ACTIVE
#           value: production-microservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: asif/testnew:latest
        # env:
        # - name: SPRING_PROFILES_ACTIVE
        #   value: production-microservice
