apiVersion: v1
kind: Service
metadata:
   name: mysql
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 31000
    name: tcp
  externalIPs:
    - 10.9.161.192