spring:
  datasource:
    url: jdbc:mysql://mysql:3306?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    schemas: test
    url: jdbc:mysql://mysql:3306?allowPublicKeyRetrieval=true&useSSL=false
    user: root
    password: password
    baseline-version: 1
    baseline-on-migrate: true
    locations:
    - classpath:db/migration
      
 
server:
  port: 8082
  

