FROM elasticsearch:7.5.1

# container creator
MAINTAINER asif

# copy the configuration file into the container
#COPY elasticsearch.yml /usr/share/elasticsearch/config
# CMD chmod 775 /usr/share/elasticsearch/data

# expose the default Elasticsearch port
EXPOSE 9200