
apiVersion: v1
kind: Service
metadata:
  name: elastic

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: elastic

  ports:
    - name: http
      port: 9200
      nodePort: 30021
  type: NodePort

#---
# apiVersion: v1
# kind: Service
# metadata:
#   name: fleetman-api-gateway

# spec:
#   # This defines which pods are going to be represented by this Service
#   # The service becomes a network endpoint for either other services
#   # or maybe external users to connect to (eg browser)
#   selector:
#     app: api-gateway

#   ports:
#     - name: http
#       port: 8080
#       nodePort: 30020

#   type: NodePort
